### PR TITLE
Adapt scalameta custom analyzer to breaking changes in scala/scala#6087.

### PR DESCRIPTION
**Pull request by hrhino**
This is current as of scala/scala@09ebc826968b.

So it turns out that I would be premature in making a 2.12.5 PR, as people are going to come around with more changes to `Typers` and `Namers` and require more integration.

Anyhow, the diff is [here](https://gist.github.com/hrhino/bfbc8ac63b7204a454ef150fb4c06e94) between the two mentioned versions, and I've pulled across all changes which affect duplicated code.

This passes all JVM tests for me (with paradise fixed at `_2.12.4` and `++2.12.5-bin-09ebc82-SNAPSHOT`).

cc/ @olafurpg and scalameta people.

### CODE REVIEW

**Comment by SethTisue** [comment]
let's try it: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2528/consoleFull

**Comment by SethTisue** [comment]
oh, we have to wait for scala/community-builds#662 to be resolved

**Comment by olafurpg** [comment]
I'm sorry for continuing to be so much trouble for the community build. I would love to get rid of our custom analyzer in semanticdb-scalac. We should be able to build on top of https://github.com/scala/scala/pull/6013 to avoid this hijacking non-sense.

One possible way to workaround this file in the CB is to comment out `hijackAnalyzer()` https://github.com/scalameta/scalameta/blob/ecdaadfba7e883a93f4ddf2be7120631975a86ed/scalameta/semanticdb-scalac-core/src/main/scala/scala/meta/internal/HijackAnalyzer.scala I suspect our test suite might even pass with that change. Another options is to leave scalameta out of the community build. I would be hesitant to try and keep the 2.12.5 copy-pasted analyzer.

**Comment by SethTisue** [comment]
new test run (w/ scala-js fix): ~~https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2531/consoleFull~~ https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2532/consoleFull

**Comment by SethTisue** [comment]
```
[info] Project scalameta-2-------------: SUCCESS (project rebuilt ok)
[info] Project scalafix----------------: SUCCESS (project rebuilt ok)
```

@olafurpg I think the cost/benefit here (to keeping scalameta in the community build) is still reasonable. we were alerted here to a real, unanticipated compatibility issue, and you've got the jump on supporting 2.12.5 (whether with a cleaner solution or more duct tape).

**Comment by SethTisue** [comment]
thanks Harrison!

**Comment by olafurpg** [comment]
Very nice. Thank you for keeping scalameta in the community build!

**Pull request merged**
